blog/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^blogs/$', views.BlogListView.as_view(), name='blog-list'),
    re_path(r'^blog/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='blog-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='author-list'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^blog/(?P<pk>\d+)/create/$', views.CommentCreate.as_view(), name='comment-create'),
    # re_path(r'^blog/(?P<pk>\d+)/create/$', views.new_comment, name='comment-create'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100, help_text='Post title')
    post = models.TextField(max_length=1000, help_text='Enter a post')
    data_post = models.DateField(default=date.today)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])

    class Meta:
        ordering = ['-data_post']

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=1000, blank=True, null=True, help_text='Enter bio of the author')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


class Comment(models.Model):
    text = models.TextField(max_length=1000, help_text='text of the comment')
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    data_post = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.text if len(self.text) < 75 else self.text[:75] + '...'

    class Meta:
        ordering = ['-data_post']

blog/forms.py
from django import forms
from .models import Comment

class NewCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text',]
        help_text = {'text': 'Create a new comment'}

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Blog, Author, Comment
# from .forms import NewCommentForm

# Create your views here.
def index(request):

    return render(request, 'index.html')


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    model = Blog

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

# @login_required
# def new_comment(request, pk):

#     if request.method == 'POST':

#         form = NewCommentForm(request.POST)
#         if form.is_valid():
#             comment = Comment()
#             comment.text = form.cleaned_data['text']
#             comment.user = request.user
#             comment.blog = get_object_or_404(Blog, pk=pk)
#             comment.save()

#             return HttpResponseRedirect(reverse('blog-detail', kwargs={'pk': pk}))
#     else:
#         form = NewCommentForm()

#     return render(request, 'blog/create_new_comment.html', {'form': form})

class CommentCreate(LoginRequiredMixin, generic.CreateView):
    model = Comment
    fields = ['text']

    def get_success_url(self):
        return reverse_lazy('blog-detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):

        form.instance.user = self.request.user
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])

        return super(CommentCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):

        context = super(CommentCreate, self).get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])

        return context

blog/templates/blog/author_detail.html
{% extends 'index.html' %}
    {% block content %}
        <h1>Author: {{author}} </h1>
        <figure style='margin-left:0;'>
            <figcaption><h2>Bio</h2></figcaption>
            <p>{{author.bio}}</p>
        </figure>
        <h2>Blog list</h2>
        <ul>
            {% for blog in author.blog_set.all %}
                <li><a href="{{ blog.get_absolute_url }}">{{ blog }}</a></li>
            {% endfor %}
        </ul>
    {% endblock %}

blog/templates/blog/author_list.html
{% extends 'index.html' %}
{% block title%}
    <title>Authors</title>
{% endblock %}
{% block content %}
    <h1>All authors</h1>
    <ul>
    {%for author in author_list %}
        <li>
            <a href="{{ author.get_absolute_url }}"> {{ author }}</a>
        </li>
    {%endfor %}
    </ul>
{%endblock %}

blog/templates/blog/blog_detail.html
{% extends 'index.html' %}
    {% block content %}
        <h1 style="margin-top:0;">{{blog.title}} </h1>
        <p><strong>Post date:</strong> {{blog.data_post}} </p>
        <p><strong>Author:</strong> {{blog.author}} </p>
        <div><strong>Description:</strong>
            <p>
                {{blog.post}}
            </p>
        </div>
        <div class="comments">
            <h2>Comments</h2>
            <hr>
            <ul style='list-style: none; padding: 0'>
                {% for comment in blog.comment_set.all%}
                    <li><span>{{comment.user}} ({{comment.data_post}}) - {{comment.text}}</span></li>
                    <hr>
                {% endfor %}
            </ul>
            {% if user.is_authenticated %}
            <p>
                <a href="{% url 'comment-create' blog.pk %}">Add new create</a>
            </p>
            {% endif %}
        </div>
    {% endblock %}

blog/templates/blog/blog_list.html
{% extends 'index.html' %}
{% block title%}
    <title>Blogs</title>
{% endblock %}
{% block content %}
    <h1>All blogs</h1>
    <ul>
    {%for blog in blog_list %}
        <li>
            <a href="{{ blog.get_absolute_url }}">{{ blog }}</a> ({{blog.data_post}}) -- <a href="{% url 'author-detail' blog.author.pk %}">{{blog.author}}</a>
        </li>
    {%endfor %}
    </ul>
{%endblock %}

blog/templates/blog/comment_form.html
{% extends 'index.html' %}

{% block content %}
<p><span>Post your comment:</span> <a href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></p>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul}}
    <input type="submit" value="Submit" />

</form>
{% endblock %}

blog/templates/blog/create_new_comment.html
{% extends "index.html" %}
{%block content%}

    <h1>New comment</h1>
    <form method="post" action=''>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit'>
    </form>
{% endblock %}

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title%}
        <title>Blog</title>
    {% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
    <div class="clearfix">
        <div class="sidebar">
            <ul class='nav'>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'blog-list' %}">Blogs</a></li>
                <li><a href="{% url 'author-list' %}">Authors</a></li>
            </ul>

            <div class="auth" style='magin-top: 40px;'>
                {% if user.is_authenticated %}
                    <p>{{ user.get_username }}</p>
                    <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}?next={{request.path}}">Login</a>
                {% endif %}
            </div>
        </div>
        <div class='content'>
            {% block content %}
            {% endblock %}
            {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
          {% endblock %}
        </div>
    </div>
</body>
</html>